### ISSUE TITLE
Causing crash in Kontact's akregator part

### ISSUE THREAD

**Issue by muesli** [Luwx/Lightly#39]
Using git master of lightly, I experience a crash when starting Kontact. The backtrace indicates it's loading akregator when it's crashing. Sadly I have no debug symbols beyond what you see in the following back trace. The app starts fine with breeze as style.

```
#4  0x00007f5e4a8662c2 in  () at /usr/lib/qt/plugins/styles/lightly.so
#5  0x00007f5db81eab86 in  () at /usr/lib/qt/plugins/akregatorpart.so
#6  0x00007f5db81ead12 in  () at /usr/lib/qt/plugins/akregatorpart.so
#7  0x00007f5db81eb639 in  () at /usr/lib/qt/plugins/akregatorpart.so
#8  0x00007f5e6b5a3dd6 in  () at /usr/lib/libQt5Core.so.5
#9  0x00007f5db2b9fbf0 in Akregator::FrameManager::signalFrameAdded(Akregator::Frame*) () at /usr/lib/libakregatorprivate.so.5
#10 0x00007f5db2bab54d in Akregator::FrameManager::slotAddFrame(Akregator::Frame*) () at /usr/lib/libakregatorprivate.so.5
#11 0x00007f5db81fce67 in Akregator::MainWidget::MainWidget(Akregator::Part*, QWidget*, Akregator::ActionManagerImpl*, QString const&) () at /usr/lib/qt/plugins/akregatorpart.so
#12 0x00007f5db81f3ddc in  () at /usr/lib/qt/plugins/akregatorpart.so
```

**Comment by kupiqu** [comment]
I reproduce this and another application also crashing is konqueror

**Comment by Luwx** [comment]
I cannot reproduce the crash,  can you test this with the latest commits?

The konqueror crash was fixed.

**Comment by kupiqu** [comment]
Mmm, it's curious because konqueror is still crashing in my system, but akreggator is not anymore

**Comment by Luwx** [comment]
I forgot to null check..
