### ISSUE TITLE
Weird behavior in some applications

### ISSUE THREAD

**Issue by Vitorvlv** [Luwx/Lightly#93]
This happens in 0.4.1 and in latest git

![Screenshot_20210326_004348](https://user-images.githubusercontent.com/26132870/112574073-55f69400-8dcc-11eb-8785-09b02be60f1c.png)

![Screenshot_20210326_004411](https://user-images.githubusercontent.com/26132870/112574103-6444b000-8dcc-11eb-9065-5b7e90bc43b0.png)

Going back to default global theme:
![Screenshot_20210326_004612](https://user-images.githubusercontent.com/26132870/112574271-b5ed3a80-8dcc-11eb-8461-2a4bc7454196.png)

![image](https://user-images.githubusercontent.com/26132870/112574311-c43b5680-8dcc-11eb-8d87-d1e3f8e3d63e.png)

**Comment by RizzoV** [comment]
This is probably a similar problem to the one I wrote about in #88. Radeon Profile and Kdenlive probably do not support transparency.

You can probably fix this problem by yourself without waiting for a fix by adding these apps to the opaquelist, as done in 68bb5fec246850b736613c653775d9fb1846cc21.

**Comment by Luwx** [comment]
The tab issue should be fixed.

**Comment by aequabit** [comment]
> This is probably a similar problem to the one I wrote about in #88. Radeon Profile and Kdenlive probably do not support transparency.
> 
> You can fix this problem by yourself without waiting for a fix by adding these apps to the opaquelist, as done in [68bb5fe](https://github.com/Luwx/Lightly/commit/68bb5fec246850b736613c653775d9fb1846cc21).

This is still an issue for me, but adding it manually solves the problem. May I ask why it's not the default?
